name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip openjdk-17-jdk zip unzip

      - name: Install Buildozer
        run: |
          pip install --user --upgrade pip setuptools wheel cython
          pip install --user buildozer

      - name: Fix PATH for Buildozer
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "PATH fixed: $HOME/.local/bin"

      - name: Setup Android SDK
        env:
          ANDROID_HOME: ${{ github.workspace }}/android-sdk
        run: |
          mkdir -p $ANDROID_HOME/cmdline-tools

          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O tools.zip
          unzip tools.zip -d $ANDROID_HOME/cmdline-tools

          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest

          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH

          yes | sdkmanager --licenses

          sdkmanager "platform-tools" \
                     "platforms;android-34" \
                     "build-tools;34.0.0"

      - name: Build APK
        env:
          ANDROID_HOME: ${{ github.workspace }}/android-sdk
          PATH: ${{ github.workspace }}/android-sdk/cmdline-tools/latest/bin:${{ github.workspace }}/android-sdk/platform-tools:$HOME/.local/bin:${{ env.PATH }}
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MultiDownloaderID
          path: bin/*.apk
